[build]
  command = "npm install && npm run export"  # This runs your build and export script
  publish = "out"                             # This is the correct directory for exported static files

# Remove redirects section if you want to keep routable HTML files
