[build]
  command = "npm install && npm run build"  # Install dependencies and build the project
  publish = ".next"                          # Use the .next directory for publishing; it contains build output