[build]
  command = "npm install && npm run build"
  publish = ".next/server/pages"  # For SSR/Node.js deployment
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pdfjs-dist", "mammoth", "buffer"]  # Add heavy deps here

[[plugins]]
  package = "@netlify/plugin-nextjs"
