# netlify.toml
[build]
  command = "npm install && npm run build"
  publish = ".next"
  functions = "netlify/functions"  # Already set, but confirm this directory exists

[functions]
  node_bundler = "esbuild"  # Optimize function bundling